path_chain: C:\\Users\\nbrigati\\OneDrive - Itron\\Desktop\\Varie\\Learn\\Blockchain\\Progetto Crypto\\chain
path_credentials: C:\\Users\\nbrigati\\OneDrive - Itron\\Desktop\\Varie\\Learn\\Blockchain\\Progetto Crypto\\credentials
name_chain: chain  # Nome del file della blockchain